# Testing Deferred Revenue in Python
Will this be easier for everyone to use than Matlab?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_excel('../data/old/base_billings.xlsx', sheet_name='bill_DC')

In [3]:
df.sample(10)

,Document Currency,Enterprise Bu,Frequency,Invoicing Fiscal Year-Period Desc,Product Configtype ID,Revenue Recognition Category New,Rule For Bill Date,Sales Type,Subscription Term,Completed Sales Doc Currency
28591,USD,Experience Cloud,ONGO,2017-05,MTHLY,D,YA,DEFERRED,12,22122.72
21155,NOK,Document Cloud,NaN,2016-07,NaN,A,NaN,DEFERRED,1,-320.72
28961,USD,Experience Cloud,ONGO,2017-10,ONORE,D,NaN,DEFERRED,0,7236153.16
23925,USD,Creative,NaN,2015-11,1Y,D,YA,DEFERRED,12,14580959.59
7395,DKK,Experience Cloud,1TME,2015-07,OCONS,NaN,NaN,PRO-SVC-INV,0,1510.00
10415,EUR,Experience Cloud,ONGO,2016-02,1Y,D,YQ,DEFERRED,12,320338.53
1471,AUD,Document Cloud,NaN,2018-08,NaN,NaN,NaN,RECOGNIZED,0,374287.00
23400,SEK,Experience Cloud,ONGO,2019-03,NaN,NaN,NaN,RECOGNIZED,0,100704.45
11547,EUR,Experience Cloud,1TME,2018-02,NaN,NaN,NaN,PRO-SVC-INV,0,21695.67
27939,USD,Experience Cloud,ONGO,2016-08,ONORE,D,YH,DEFERRED,0,23561.80

## Filter that removes any currency that has  < 10 transactions.

In [5]:
# creates a list of the currencies and the number of transactions for each currency
vc = df['Document Currency'].value_counts()

In [6]:
# Create variable that is true if the number of transaction is greater than 10, false otherwise
keep_these = vc.values > 10
# filtering only currencies that were greater than 10
keep_curr = vc[keep_these]
a = keep_curr.index
# filtering the dataframe to remove any of teh currencies not in our list
df = df[df['Document Currency'].isin(a)]

## Just keeping track of the currencies we removed in our model_dict data strucutre

In [22]:
remove_these = vc.values <= 10
model_dict = {'curr_removed': list(vc[remove_these].index)}
model_dict

{'curr_removed': ['CLP', 'COP', 'ARS', 'PEN', 'INR', 'BMD', 'MXP']}

# Removing any of the values that are zero

In [25]:
print('This is the length of the dataframe before removing zeros: ', len(df))
df = df[df['Completed Sales Doc Currency']!=0]
print('This is the length of the dataframe after removing zeros: ', len(df))

This is the length of the dataframe before removing zeros:  31418
This is the length of the dataframe after removing zeros:  28896

In [27]:
df.sample(20)

,Document Currency,Enterprise Bu,Frequency,Invoicing Fiscal Year-Period Desc,Product Configtype ID,Revenue Recognition Category New,Rule For Bill Date,Sales Type,Subscription Term,Completed Sales Doc Currency
11363,EUR,Experience Cloud,1TME,2017-10,OUNIV,NaN,NaN,PRO-SVC-INV,0,-8590.40
18920,JPY,Document Cloud,NaN,2018-09,NaN,D,YA,DEFERRED,12,18271148.00
30262,USD,LiveCycle,CERT,2017-10,NaN,NaN,NaN,RECOGNIZED,0,7000.00
18414,JPY,Document Cloud,NaN,2015-12,1Y,D,Y3,DEFERRED,1,11053675.00
16986,GBP,Print & Publishing,NaN,2018-03,MTHLY,D,Y3,DEFERRED,1,40.49
9925,EUR,Document Cloud,NaN,2018-12,1Y,D,NaN,DEFERRED,12,9516755.29
13449,GBP,Creative,NaN,2016-04,1Y,D,Y3,DEFERRED,1,5841913.75
37,AUD,Creative,NaN,2015-07,1Y,D,Y3,DEFERRED,1,3907210.44
24600,USD,Creative,1TME,2017-03,ONORE,NaN,NaN,RECOGNIZED,0,7458.22
13893,GBP,Creative,NaN,2018-06,1Y,D,NaN,DEFERRED,0,173649.96
18667,JPY,Document Cloud,NaN,2017-05,IDRT,NaN,NaN,RECOGNIZED,0,253980.00
16063,GBP,Experience Cloud,ONGO,2018-04,ONORE,D,YQ,DEFERRED,0,966.00
22509,SEK,Creative,NaN,2018-07,MTHLY,A,NaN,DEFERRED,1,-27771.75
1737,AUD,Experience Cloud,NaN,2015-10,NaN,NaN,NaN,RECOGNIZED,0,409.00
14019,GBP,Creative,NaN,2018-12,MTHLY,NaN,NaN,DEFERRED,1,-134.98
7002,DKK,Document Cloud,NaN,2016-02,NaN,D,YA,DEFERRED,12,245845.95
10475,EUR,Experience Cloud,ONGO,2016-03,ONORE,D,NaN,DEFERRED,0,3799264.73
29108,USD,Experience Cloud,NaN,2018-01,NaN,NaN,NaN,RECOGNIZED,0,61259.80
29866,USD,Experience Cloud,1TME,2018-12,OUNIV,F,NaN,DEFERRED,0,-1.00
9400,EUR,Document Cloud,NaN,2016-10,NaN,NaN,NaN,RECOGNIZED,0,2042280.26

## Clearing out the Non-Revenue billings from the file
 - No Idea what these are

In [29]:
df['Sales Type'].value_counts()

DEFERRED       22919
RECOGNIZED      5041
PRO-SVC-INV      844
NON-REV           92
Name: Sales Type, dtype: int64

In [30]:
print('Length of the dataframe before removing non-revenue billings: ', len(df))
df = df[df['Sales Type']!='NON-REV']
print('Length of the dataframe after removing non-revenue billings:  ', len(df))

Length of the dataframe before removing non-revenue billings:  28896
Length of the dataframe after removing non-revenue billings:  28804

## Starting to group the revenue by period, industry, etc

31418