# Building the deferred waterfall from the forecast

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

import pickle

input_df_dict_long = {'model_dict': model_dict,
                 'billings':df_billings, 
                 'ADBE_cal':df_cal,
                 'bookings': df_bookings,
                 'FX_forwards': df_FX_fwds,
                 'FX_rates': df_FX_rates,
                 'forecast': df_fcst,
                 'final': df
                }

In [2]:
saved_dict = pickle.load( open('../data/processed/initial_forecast.p', 'rb'))

In [4]:
saved_dict.keys()

dict_keys(['model_dict', 'billings', 'ADBE_cal', 'bookings', 'FX_forwards', 'FX_rates', 'forecast'])

In [5]:
df_billings = saved_dict['billings']
df_billings.head(5)

,curr,BU,period,recognized_DC,recognized_US,service_DC,service_US,deferred_B_DC,deferred_B_US,deferred_1M_DC,...,deferred_2Y_DC,deferred_3Y_DC,deferred_1M_US,deferred_3M_US,deferred_6M_US,deferred_1Y_US,deferred_2Y_US,deferred_3Y_US,Period_Weeks,is_forecast
18,ARS,Creative,2017-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
11,ARS,Creative,2017-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5,ARS,Creative,2017-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0,ARS,Creative,2017-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,ARS,Creative,2017-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [6]:
df_fcst = saved_dict['forecast']
df_fcst.head(10)

,curr,BU,period,recognized_DC,service_DC,deferred_B_DC,deferred_1M_DC,deferred_3M_DC,deferred_6M_DC,deferred_1Y_DC,...,is_forecast,recognized_US,service_US,deferred_B_US,deferred_1M_US,deferred_3M_US,deferred_6M_US,deferred_1Y_US,deferred_2Y_US,deferred_3Y_US
0,ARS,Creative,2020-04,0.00,0.0,0.0,1.835209e+07,0.0,0.0,1112854.12,...,1,0.000000,0.0,0.0,281826.091681,0.0,0.0,17089.676820,0.0,0.0
1,ARS,Creative,2020-05,0.00,0.0,0.0,1.972401e+07,0.0,0.0,1595808.00,...,1,0.000000,0.0,0.0,291566.159398,0.0,0.0,23589.702654,0.0,0.0
2,ARS,Creative,2020-06,0.00,0.0,0.0,2.636992e+07,0.0,0.0,1654238.00,...,1,0.000000,0.0,0.0,375754.937710,0.0,0.0,23571.863177,0.0,0.0
3,ARS,Creative,2020-07,6786.00,0.0,0.0,2.246786e+07,0.0,0.0,953875.89,...,1,92.981173,0.0,0.0,307852.569710,0.0,0.0,13069.923230,0.0,0.0
4,ARS,Creative,2020-08,16472.00,0.0,0.0,2.383978e+07,0.0,0.0,963180.00,...,1,217.347321,0.0,0.0,314564.807679,0.0,0.0,12709.118067,0.0,0.0
5,ARS,Creative,2020-09,19205.00,0.0,0.0,3.151462e+07,0.0,0.0,2263704.00,...,1,244.367802,0.0,0.0,400997.595536,0.0,0.0,28803.768392,0.0,0.0
6,ARS,Creative,2020-10,30382.19,0.0,0.0,2.658362e+07,0.0,0.0,1318346.81,...,1,377.994658,0.0,0.0,330735.397287,0.0,0.0,16401.979290,0.0,0.0
7,ARS,Creative,2020-11,59049.00,0.0,0.0,2.795554e+07,0.0,0.0,1494162.20,...,1,718.671974,0.0,0.0,340240.521630,0.0,0.0,18185.108938,0.0,0.0
8,ARS,Creative,2020-12,71355.57,0.0,0.0,3.665933e+07,0.0,0.0,3154860.03,...,1,849.968910,0.0,0.0,436676.306451,0.0,0.0,37579.868566,0.0,0.0
9,ARS,Creative,2021-01,79224.95,0.0,0.0,3.837423e+07,0.0,0.0,916705.92,...,1,907.591699,0.0,0.0,439610.620247,0.0,0.0,10501.675079,0.0,0.0

In [ ]:
df_waterfall =

# NEED TO DECIDE IF I WANT TO CREATE THE ENTIRE HISTORY OF THE WATERFALL OR NOT

As a check, I should build it historically

- rows are dates, columns are future amounts expected to be amortized
- by currency, BU

Columns
 - total
 - p_1
 - p_2
 - p_3 (etc out 36 months)
 
 - We are taking the USD equivalent and splitting this into the other areas
 
##### Monthly Billings
- 1/2 of the current month + 1/2 of the prior month

##### Annual Billings
- 1/12 of the current annual billings + 11 of the last annual billings + 1/12 of the year prior billings

### Quarterly

In [10]:
wf_columns = ['Total']
for i in np.arange(36):
    this_column = 'p_'+ str(i+1)
    wf_columns.append(this_column)

print(wf_columns)

['Total', 'p_1', 'p_2', 'p_3', 'p_4', 'p_5', 'p_6', 'p_7', 'p_8', 'p_9', 'p_10', 'p_11', 'p_12', 'p_13', 'p_14', 'p_15', 'p_16', 'p_17', 'p_18', 'p_19', 'p_20', 'p_21', 'p_22', 'p_23', 'p_24', 'p_25', 'p_26', 'p_27', 'p_28', 'p_29', 'p_30', 'p_31', 'p_32', 'p_33', 'p_34', 'p_35', 'p_36']

In [12]:
# The index is not necessary to create this dataframe

In [13]:
def find_unique_curr_and_BU(df_billings):
    v_BU = df_billings['BU'].copy()
    v_curr = df_billings['curr'].copy()
    v_both = v_BU + v_curr
    v_unique = v_both.unique()

    v_un_BU = [sub[:-3] for sub in v_unique]
    v_un_curr = [sub[-3:] for sub in v_unique]

    return v_un_BU, v_un_curr