In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
import_thing = pickle.load(open('/Volumes/Treasury/Financial_Database/Deferred_Revenue/Inputs/Data_2020_p12/processed/intermediate/int_output_4.p', "rb"))
df_billings = import_thing["billings"]
df_bookings = import_thing["bookings"]

In [9]:
import_thing.keys()

dict_keys(['model_dict', 'billings', 'ADBE_cal', 'bookings', 'FX_forwards', 'FX_rates'])

In [10]:
df_FX_fwds = import_thing['FX_forwards']
df_FX_fwds

   curr       forward
0   AED      3.674341
1   AUD      1.396280
2   BBD      2.000000
3   BMD      1.000000
4   BRL      5.794235
..  ...           ...
61  BDT     84.848700
62  BGN      1.669594
63  TZS   2455.056100
64  VND  23278.970000
65  PKR    166.878700

[66 rows x 2 columns]

In [3]:
df_billings.head(10)

,curr,BU,period,recognized_DC,recognized_US,service_DC,service_US,_merge,deferred_1M_DC,deferred_3M_DC,...,deferred_1Y_DC,deferred_2Y_DC,deferred_3Y_DC,deferred_1M_US,deferred_3M_US,deferred_6M_US,deferred_1Y_US,deferred_2Y_US,deferred_3Y_US,Period_Weeks
0,ARS,Creative,2019-03,0.00,0.00,0.0,0.0,left_only,419565.00,0.0,...,241380.00,0.0,0.0,10774.56,0.0,0.0,6194.45,0.0,0.0,5
1,ARS,Creative,2019-04,0.00,0.00,0.0,0.0,left_only,1894409.00,0.0,...,1112854.12,0.0,0.0,46686.26,0.0,0.0,27486.58,0.0,0.0,4
2,ARS,Creative,2019-05,0.00,0.00,0.0,0.0,left_only,3205378.29,0.0,...,1595808.00,0.0,0.0,75114.30,0.0,0.0,37319.65,0.0,0.0,4
3,ARS,Creative,2019-06,0.00,0.00,0.0,0.0,left_only,5731933.57,0.0,...,1654238.00,0.0,0.0,128084.89,0.0,0.0,36923.24,0.0,0.0,5
4,ARS,Creative,2019-07,20746.00,476.76,0.0,0.0,left_only,6453291.31,0.0,...,953875.89,0.0,0.0,146091.12,0.0,0.0,21566.14,0.0,0.0,4
5,ARS,Creative,2019-08,30432.00,722.13,0.0,0.0,left_only,7305797.08,0.0,...,963180.00,0.0,0.0,173274.71,0.0,0.0,22781.91,0.0,0.0,4
6,ARS,Creative,2019-09,19205.00,405.51,0.0,0.0,left_only,10654985.72,0.0,...,2263704.00,0.0,0.0,217611.17,0.0,0.0,46297.25,0.0,0.0,5
7,ARS,Creative,2019-10,44342.19,779.22,0.0,0.0,left_only,10302933.07,0.0,...,1318346.81,0.0,0.0,181706.80,0.0,0.0,23376.52,0.0,0.0,4
8,ARS,Creative,2019-11,136231.00,2367.86,0.0,0.0,left_only,11340099.40,0.0,...,1494162.20,0.0,0.0,196031.97,0.0,0.0,25782.35,0.0,0.0,4
9,ARS,Creative,2019-12,212153.57,3555.93,0.0,0.0,left_only,16809972.33,0.0,...,3154860.03,0.0,0.0,281781.98,0.0,0.0,52987.34,0.0,0.0,5

In [4]:
df_bookings.tail(20)

,BU,segment,geo,region,country,Quarter,value,Currency
264,Digital Experience,Experience Cloud,ASIA,ANZ,Aus and New Zealand,Q4_2021,3.089987e+07,AUD
265,Digital Experience,Experience Cloud,ASIA,Greater China,China,Q4_2021,2.573108e+06,USD
266,Digital Experience,Experience Cloud,ASIA,Greater China,Hong Kong & Taiwan,Q4_2021,2.866115e+06,USD
267,Digital Experience,Experience Cloud,ASIA,India,India,Q4_2021,8.351491e+06,USD
268,Digital Experience,Experience Cloud,ASIA,Korea,Korea,Q4_2021,2.086450e+06,USD
269,Digital Experience,Experience Cloud,ASIA,SEA,Southeast Asia,Q4_2021,7.397304e+06,USD
270,Digital Experience,Experience Cloud,EMEA,Central Europe,Eastern Europe,Q4_2021,2.088590e+06,EUR
271,Digital Experience,Experience Cloud,EMEA,Central Europe,Germany,Q4_2021,2.526351e+07,EUR
272,Digital Experience,Experience Cloud,EMEA,Central Europe,Russia & CIS,Q4_2021,4.308339e+05,USD
273,Digital Experience,Experience Cloud,EMEA,Central Europe,Switzerland,Q4_2021,8.457069e+06,EUR
274,Digital Experience,Experience Cloud,EMEA,Med,Mediterranean,Q4_2021,-3.880000e+06,EUR
275,Digital Experience,Experience Cloud,EMEA,Northern Europe,Middle East,Q4_2021,3.315922e+06,USD
276,Digital Experience,Experience Cloud,EMEA,Northern Europe,Nordic,Q4_2021,1.274425e+07,EUR
277,Digital Experience,Experience Cloud,EMEA,Northern Europe,SSA & Israel,Q4_2021,1.164350e+06,USD
278,Digital Experience,Experience Cloud,EMEA,Northern Europe,United Kingdom,Q4_2021,5.307982e+07,GBP
279,Digital Experience,Experience Cloud,EMEA,Southwest Europe,Benelux,Q4_2021,1.010811e+07,EUR
280,Digital Experience,Experience Cloud,EMEA,Southwest Europe,France,Q4_2021,1.481993e+07,EUR
281,Digital Experience,Experience Cloud,EMEA,Southwest Europe,Iberica,Q4_2021,6.099113e+06,EUR
282,Digital Experience,Experience Cloud,EMEA,Southwest Europe,Italy,Q4_2021,5.946688e+06,EUR
283,Digital Experience,Experience Cloud,JPN,Japan,Japan,Q4_2021,2.487557e+07,JPY

# Adding the book periods function here

In [5]:
def build_booking_periods(df_bookings, df_billings):
    '''
    STEPS
        Creating data to add to the billings dataframe to incorporate period by period billings
        Fills in the df_book_period dataframe with the quarterly bookings numbers for each BU and currency
        Creating lists of periods and quarters needed to fill out the df_book_period dataframe
        Adding the booking periods to the dataframe. The bookings are split into periods based on last years percentage of 1 year deferred billings within the quarter.
            For example: P1 = 25%, P2 = 30%, P3 = 45% such that the sum is equal to the total quarterly billings last year
        Cleaning up the dataframe by dropping the columns we no longer need
    '''
    #BELOW WAS FOR WHEN KAREN DID THE BILLINGS AND WE HAD BU as Creative, Doc Cloud, etc
    #list_BUs = df_bookings["BU"].unique()
    # this is now called segment
    list_BUs = df_bookings["segment"].unique()
    list_curr = df_bookings["Currency"].unique()

    print("This is the list of BUs in the bookings dataframe: ", list_BUs)
    print("This is the list of currencies in the bookings dataframe: ", list_curr)

    # NOTE:  This is just creating the space in the dataframe for the data. We will fill it in later
    # creating dataframe of zeros
    l_BU = []
    l_curr = []
    for BU in list_BUs:
        for curr in list_curr:
            l_BU.append(BU)
            l_curr.append(curr)
    # print(l_BU)
    # print(l_curr)
    l_zero = np.zeros(len(l_BU))

    data = {
        "segment": l_BU,
        "curr": l_curr,
        "Q1": l_zero,
        "Q2": l_zero,
        "Q3": l_zero,
        "Q4": l_zero,
        "P01": l_zero,
        "P02": l_zero,
        "P03": l_zero,
        "P04": l_zero,
        "P05": l_zero,
        "P06": l_zero,
        "P07": l_zero,
        "P08": l_zero,
        "P09": l_zero,
        "P10": l_zero,
        "P11": l_zero,
        "P12": l_zero,
    }

    df_book_period = pd.DataFrame(data)

    #df_book_period.head(14)

    #df_bookings.BU.value_counts()

    # Fills in the df_book_period dataframe with the quarterly bookings numbers for each BU and currency
    # fill in the quarters
    for i in range(len(df_book_period["segment"])):
        this_segment = df_book_period["segment"][i]
        this_curr = df_book_period["curr"][i]
        this_slice = df_bookings[
            (df_bookings["segment"] == this_segment) & (df_bookings["Currency"] == this_curr)
            ]

        this_Q1 = this_slice[this_slice["Quarter"] == "Q1_2021"]
        sum_Q1 = this_Q1["value"].sum()
        df_book_period["Q1"].loc[i] = sum_Q1

        this_Q2 = this_slice[this_slice["Quarter"] == "Q2_2021"]
        sum_Q2 = this_Q2["value"].sum()
        df_book_period["Q2"].loc[i] = sum_Q2

        this_Q3 = this_slice[this_slice["Quarter"] == "Q3_2021"]
        sum_Q3 = this_Q3["value"].sum()
        df_book_period["Q3"].loc[i] = sum_Q3

        this_Q4 = this_slice[this_slice["Quarter"] == "Q4_2021"]
        sum_Q4 = this_Q4["value"].sum()
        df_book_period["Q4"].loc[i] = sum_Q4

    df_book_period.head(30)

    print("Q1 total bookings ", df_book_period["Q1"].sum())
    print("Q2 total bookings ", df_book_period["Q2"].sum())
    print("Q3 total bookings ", df_book_period["Q3"].sum())
    print("Q4 total bookings ", df_book_period["Q4"].sum())

    # ##### Creating lists of periods and quarters needed to fill out the df_book_period dataframe
    # list of quarters for the percentages

    #TODO: Add these to the config file!!!
    list_q1 = ["2021-01", "2021-02", "2021-03"]
    list_q2 = ["2021-04", "2021-05", "2021-06"]
    list_q3 = ["2021-07", "2021-08", "2021-09"]
    list_q4 = ["2021-10", "2021-11", "2021-12"]

    # list periods should be the year prior periods. This is what gets looked up in df_billiings
    list_periods = [
        "2020-01",
        "2020-02",
        "2020-03",
        "2020-04",
        "2020-05",
        "2020-06",
        "2020-07",
        "2020-08",
        "2020-09",
        "2020-10",
        "2020-11",
        "2020-12",
    ]

    list_p_headers = [
        "P01",
        "P02",
        "P03",
        "P04",
        "P05",
        "P06",
        "P07",
        "P08",
        "P09",
        "P10",
        "P11",
        "P12",
    ]

    list_q_headers = [
        "Q1",
        "Q1",
        "Q1",
        "Q2",
        "Q2",
        "Q2",
        "Q3",
        "Q3",
        "Q3",
        "Q4",
        "Q4",
        "Q4",
    ]

    # ##### adding the booking periods to the dataframe. The bookings are split into periods based on last years percentage of 1 year deferred billings within the quarter.
    # For example: P1 = 25%, P2 = 30%, P3 = 45% such that the sum is equal to the total quarterly billings last year
    for i in range(len(df_book_period["segment"])):

        this_segment = df_book_period["segment"][i]
        this_curr = df_book_period["curr"][i]

        this_slice = df_billings[
            (df_billings["BU"] == this_segment) & (df_billings["curr"] == this_curr)
            ]

        for j in range(len(list_periods)):
            this_period = list_periods[j]
            this_header = list_p_headers[j]
            this_quarter = list_q_headers[j]
            this_P_slice = this_slice[this_slice["period"] == this_period]
            df_book_period.loc[[i], [this_header]] = this_P_slice["deferred_1Y_DC"].sum()

    df_book_period["bill_Q1_sum"] = (
            df_book_period["P01"] + df_book_period["P02"] + df_book_period["P03"]
    )
    df_book_period["bill_Q2_sum"] = (
            df_book_period["P04"] + df_book_period["P05"] + df_book_period["P06"]
    )
    df_book_period["bill_Q3_sum"] = (
            df_book_period["P07"] + df_book_period["P08"] + df_book_period["P09"]
    )
    df_book_period["bill_Q4_sum"] = (
            df_book_period["P10"] + df_book_period["P11"] + df_book_period["P12"]
    )

    df_book_period["P01"] = (
            df_book_period["Q1"] * df_book_period["P01"] / df_book_period["bill_Q1_sum"]
    )
    df_book_period["P02"] = (
            df_book_period["Q1"] * df_book_period["P02"] / df_book_period["bill_Q1_sum"]
    )
    df_book_period["P03"] = (
            df_book_period["Q1"] * df_book_period["P03"] / df_book_period["bill_Q1_sum"]
    )

    df_book_period["P04"] = (
            df_book_period["Q2"] * df_book_period["P04"] / df_book_period["bill_Q2_sum"]
    )
    df_book_period["P05"] = (
            df_book_period["Q2"] * df_book_period["P05"] / df_book_period["bill_Q2_sum"]
    )
    df_book_period["P06"] = (
            df_book_period["Q2"] * df_book_period["P06"] / df_book_period["bill_Q2_sum"]
    )

    df_book_period["P07"] = (
            df_book_period["Q3"] * df_book_period["P07"] / df_book_period["bill_Q3_sum"]
    )
    df_book_period["P08"] = (
            df_book_period["Q3"] * df_book_period["P08"] / df_book_period["bill_Q3_sum"]
    )
    df_book_period["P09"] = (
            df_book_period["Q3"] * df_book_period["P09"] / df_book_period["bill_Q3_sum"]
    )

    df_book_period["P10"] = (
            df_book_period["Q4"] * df_book_period["P10"] / df_book_period["bill_Q4_sum"]
    )
    df_book_period["P11"] = (
            df_book_period["Q4"] * df_book_period["P11"] / df_book_period["bill_Q4_sum"]
    )
    df_book_period["P12"] = (
            df_book_period["Q4"] * df_book_period["P12"] / df_book_period["bill_Q4_sum"]
    )

    df_book_period.tail(10)

    # ###### Cleaning up the dataframe by dropping the columns we no longer need
    df_book_period.drop(
        ["bill_Q1_sum", "bill_Q2_sum", "bill_Q3_sum", "bill_Q4_sum"], axis=1, inplace=True
    )



    return df_book_period

In [6]:
df_book_period = build_booking_periods(df_bookings, df_billings)

This is the list of BUs in the bookings dataframe:  ['Creative' 'Document Cloud' 'Experience Cloud']
This is the list of currencies in the bookings dataframe:  ['USD' 'AUD' 'EUR' 'GBP' 'JPY']
Q1 total bookings  372420911.4806338
Q2 total bookings  458859042.3446756
Q3 total bookings  522781917.4306791
Q4 total bookings  737327298.5342783

/Users/davesmith/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [7]:
df_book_period

,segment,curr,Q1,Q2,Q3,Q4,P01,P02,P03,P04,P05,P06,P07,P08,P09,P10,P11,P12
0,Creative,USD,3.353217e+07,3.647937e+07,4.594678e+07,5.024712e+07,1.138063e+07,8.383721e+06,1.376782e+07,1.157768e+07,8.931597e+06,1.597009e+07,1.222459e+07,1.199205e+07,2.173014e+07,1.599765e+07,1.541702e+07,1.883245e+07
1,Creative,AUD,1.647356e+06,2.063449e+06,2.171380e+06,3.754770e+06,5.323724e+05,3.971506e+05,7.178325e+05,5.519514e+05,6.235560e+05,8.879415e+05,5.170004e+05,6.972151e+05,9.571644e+05,8.439141e+05,8.495364e+05,2.061319e+06
2,Creative,EUR,6.584741e+06,8.341990e+06,1.224934e+07,2.079688e+07,2.191754e+06,1.810889e+06,2.582098e+06,2.530085e+06,2.210486e+06,3.601419e+06,3.879535e+06,3.469331e+06,4.900477e+06,5.170372e+06,4.829879e+06,1.079663e+07
3,Creative,GBP,3.448298e+06,3.228927e+06,3.991542e+06,6.352543e+06,1.231674e+06,9.551193e+05,1.261506e+06,8.898726e+05,1.001382e+06,1.337673e+06,7.043781e+05,7.962808e+05,2.490883e+06,1.722796e+06,1.878605e+06,2.751143e+06
4,Creative,JPY,3.833277e+06,7.528496e+06,4.192102e+06,5.252535e+06,1.058255e+06,9.096653e+05,1.865357e+06,2.044769e+06,2.513401e+06,2.970326e+06,1.148877e+06,1.285973e+06,1.757253e+06,1.503187e+06,1.262389e+06,2.486959e+06
5,Document Cloud,USD,2.362795e+07,2.858595e+07,4.165213e+07,5.662069e+07,7.541640e+06,5.629985e+06,1.045632e+07,7.436849e+06,8.368598e+06,1.278051e+07,1.273265e+07,9.906888e+06,1.901259e+07,1.518978e+07,1.801767e+07,2.341324e+07
6,Document Cloud,AUD,1.438565e+06,1.632384e+06,1.945140e+06,2.228751e+06,5.211134e+05,3.141580e+05,6.032935e+05,4.492348e+05,4.096821e+05,7.734669e+05,5.777254e+05,6.440612e+05,7.233531e+05,4.888265e+05,6.306341e+05,1.109291e+06
7,Document Cloud,EUR,5.050085e+06,6.962306e+06,7.381536e+06,1.473998e+07,1.633802e+06,1.598216e+06,1.818066e+06,1.565634e+06,1.818197e+06,3.578476e+06,2.314511e+06,2.118408e+06,2.948617e+06,3.287449e+06,3.029456e+06,8.423078e+06
8,Document Cloud,GBP,2.942191e+06,3.477646e+06,3.161506e+06,6.194697e+06,1.299257e+06,6.775934e+05,9.653405e+05,6.762189e+05,1.043654e+06,1.757773e+06,9.453755e+05,8.588065e+05,1.357324e+06,1.311304e+06,1.729536e+06,3.153857e+06
9,Document Cloud,JPY,1.677403e+06,2.320611e+06,2.051876e+06,2.582073e+06,3.636555e+05,2.512814e+05,1.062466e+06,5.513015e+05,8.697112e+05,8.995979e+05,6.581845e+05,5.057432e+05,8.879481e+05,5.579653e+05,7.609803e+05,1.263127e+06
10,Experience Cloud,USD,2.127692e+08,2.472166e+08,2.894203e+08,3.780547e+08,7.712481e+07,8.015540e+07,5.548903e+07,1.110184e+08,8.157082e+07,5.462740e+07,9.780503e+07,8.820072e+07,1.034146e+08,1.305203e+08,1.026679e+08,1.448665e+08
11,Experience Cloud,AUD,1.055118e+07,1.507311e+07,1.884138e+07,3.089987e+07,3.446806e+06,3.402949e+06,3.701419e+06,4.984379e+06,4.899854e+06,5.188874e+06,5.215528e+06,4.614628e+06,9.011228e+06,4.345049e+06,1.107869e+07,1.547613e+07
12,Experience Cloud,EUR,3.488288e+07,4.826918e+07,4.372513e+07,8.164726e+07,7.500921e+06,1.825072e+07,9.131240e+06,1.604028e+07,1.199285e+07,2.023605e+07,1.485957e+07,1.798871e+07,1.087686e+07,2.234278e+07,3.210460e+07,2.719988e+07
13,Experience Cloud,GBP,2.068045e+07,3.308872e+07,3.102067e+07,5.307982e+07,5.226887e+06,5.871527e+06,9.582034e+06,9.397012e+06,1.127723e+07,1.241447e+07,6.634316e+06,1.260052e+07,1.178584e+07,2.344689e+07,1.039947e+07,1.923345e+07
14,Experience Cloud,JPY,9.755124e+06,1.459026e+07,1.503107e+07,2.487557e+07,3.458060e+06,4.090409e+06,2.206655e+06,2.648337e+06,1.075075e+07,1.191180e+06,3.056135e+06,6.885649e+06,5.089288e+06,5.734443e+06,9.876115e+06,9.265016e+06

# convert_bookings_to_DC here

In [11]:
def convert_bookings_to_DC(df_book_period, df_FX_fwds):
    '''
    The bookings forecast is in USD, but we need document currency bookings.
    This function takes the df_book_period dataframe and adds the DC equivalent
    to all of the bookings by using the plan FX forward rates dataframe df_FX_fwds

    '''
    df_FX_fwds.set_index("curr", inplace=True)

    list_fwds = []
    for i in range(len(df_book_period["curr"])):
        this_curr = df_book_period["curr"][i]

        if this_curr == "USD":
            this_fwd = 1
        else:
            this_fwd = df_FX_fwds.loc[this_curr, "forward"]

        list_fwds.append(this_fwd)
    df_book_period["FX_fwd_rate"] = list_fwds

    df_book_period["P01_DC"] = df_book_period["P01"] * df_book_period["FX_fwd_rate"]
    df_book_period["P02_DC"] = df_book_period["P02"] * df_book_period["FX_fwd_rate"]
    df_book_period["P03_DC"] = df_book_period["P03"] * df_book_period["FX_fwd_rate"]
    df_book_period["P04_DC"] = df_book_period["P04"] * df_book_period["FX_fwd_rate"]
    df_book_period["P05_DC"] = df_book_period["P05"] * df_book_period["FX_fwd_rate"]
    df_book_period["P06_DC"] = df_book_period["P06"] * df_book_period["FX_fwd_rate"]
    df_book_period["P07_DC"] = df_book_period["P07"] * df_book_period["FX_fwd_rate"]
    df_book_period["P08_DC"] = df_book_period["P08"] * df_book_period["FX_fwd_rate"]
    df_book_period["P09_DC"] = df_book_period["P09"] * df_book_period["FX_fwd_rate"]
    df_book_period["P10_DC"] = df_book_period["P10"] * df_book_period["FX_fwd_rate"]
    df_book_period["P11_DC"] = df_book_period["P11"] * df_book_period["FX_fwd_rate"]
    df_book_period["P12_DC"] = df_book_period["P12"] * df_book_period["FX_fwd_rate"]

    # The df_book_period dataframe now has columns for bookings each period
    # in both local currency and document currency

    return df_book_period

In [12]:
df_book_period = convert_bookings_to_DC(df_book_period, df_FX_fwds)

In [14]:
df_book_period.head(20)

,segment,curr,Q1,Q2,Q3,Q4,P01,P02,P03,P04,...,P03_DC,P04_DC,P05_DC,P06_DC,P07_DC,P08_DC,P09_DC,P10_DC,P11_DC,P12_DC
0,Creative,USD,3.353217e+07,3.647937e+07,4.594678e+07,5.024712e+07,1.138063e+07,8.383721e+06,1.376782e+07,1.157768e+07,...,1.376782e+07,1.157768e+07,8.931597e+06,1.597009e+07,1.222459e+07,1.199205e+07,2.173014e+07,1.599765e+07,1.541702e+07,1.883245e+07
1,Creative,AUD,1.647356e+06,2.063449e+06,2.171380e+06,3.754770e+06,5.323724e+05,3.971506e+05,7.178325e+05,5.519514e+05,...,1.002295e+06,7.706787e+05,8.706587e+05,1.239815e+06,7.218774e+05,9.735075e+05,1.336469e+06,1.178340e+06,1.186191e+06,2.878179e+06
2,Creative,EUR,6.584741e+06,8.341990e+06,1.224934e+07,2.079688e+07,2.191754e+06,1.810889e+06,2.582098e+06,2.530085e+06,...,2.195506e+06,2.151281e+06,1.879532e+06,3.062214e+06,3.298691e+06,2.949903e+06,4.166778e+06,4.396264e+06,4.106749e+06,9.180156e+06
3,Creative,GBP,3.448298e+06,3.228927e+06,3.991542e+06,6.352543e+06,1.231674e+06,9.551193e+05,1.261506e+06,8.898726e+05,...,9.660711e+05,6.814716e+05,7.668663e+05,1.024401e+06,5.394184e+05,6.097982e+05,1.907538e+06,1.319331e+06,1.438651e+06,2.106847e+06
4,Creative,JPY,3.833277e+06,7.528496e+06,4.192102e+06,5.252535e+06,1.058255e+06,9.096653e+05,1.865357e+06,2.044769e+06,...,1.944356e+08,2.131367e+08,2.619846e+08,3.096122e+08,1.197533e+08,1.340435e+08,1.831674e+08,1.566849e+08,1.315852e+08,2.592284e+08
5,Document Cloud,USD,2.362795e+07,2.858595e+07,4.165213e+07,5.662069e+07,7.541640e+06,5.629985e+06,1.045632e+07,7.436849e+06,...,1.045632e+07,7.436849e+06,8.368598e+06,1.278051e+07,1.273265e+07,9.906888e+06,1.901259e+07,1.518978e+07,1.801767e+07,2.341324e+07
6,Document Cloud,AUD,1.438565e+06,1.632384e+06,1.945140e+06,2.228751e+06,5.211134e+05,3.141580e+05,6.032935e+05,4.492348e+05,...,8.423667e+05,6.272576e+05,5.720309e+05,1.079976e+06,8.066665e+05,8.992897e+05,1.010003e+06,6.825387e+05,8.805417e+05,1.548881e+06
7,Document Cloud,EUR,5.050085e+06,6.962306e+06,7.381536e+06,1.473998e+07,1.633802e+06,1.598216e+06,1.818066e+06,1.565634e+06,...,1.545865e+06,1.331227e+06,1.545977e+06,3.042706e+06,1.967982e+06,1.801240e+06,2.507150e+06,2.795252e+06,2.575886e+06,7.161975e+06
8,Document Cloud,GBP,2.942191e+06,3.477646e+06,3.161506e+06,6.194697e+06,1.299257e+06,6.775934e+05,9.653405e+05,6.762189e+05,...,7.392655e+05,5.178538e+05,7.992389e+05,1.346116e+06,7.239761e+05,6.576809e+05,1.039450e+06,1.004207e+06,1.324493e+06,2.415249e+06
9,Document Cloud,JPY,1.677403e+06,2.320611e+06,2.051876e+06,2.582073e+06,3.636555e+05,2.512814e+05,1.062466e+06,5.513015e+05,...,1.107462e+08,5.746497e+07,9.065444e+07,9.376968e+07,6.860593e+07,5.271619e+07,9.255536e+07,5.815957e+07,7.932086e+07,1.316622e+08
10,Experience Cloud,USD,2.127692e+08,2.472166e+08,2.894203e+08,3.780547e+08,7.712481e+07,8.015540e+07,5.548903e+07,1.110184e+08,...,5.548903e+07,1.110184e+08,8.157082e+07,5.462740e+07,9.780503e+07,8.820072e+07,1.034146e+08,1.305203e+08,1.026679e+08,1.448665e+08
11,Experience Cloud,AUD,1.055118e+07,1.507311e+07,1.884138e+07,3.089987e+07,3.446806e+06,3.402949e+06,3.701419e+06,4.984379e+06,...,5.168218e+06,6.959589e+06,6.841568e+06,7.245122e+06,7.282337e+06,6.443313e+06,1.258220e+07,6.066906e+06,1.546896e+07,2.160901e+07
12,Experience Cloud,EUR,3.488288e+07,4.826918e+07,4.372513e+07,8.164726e+07,7.500921e+06,1.825072e+07,9.131240e+06,1.604028e+07,...,7.764111e+06,1.363873e+07,1.019728e+07,1.720631e+07,1.263479e+07,1.529544e+07,9.248375e+06,1.899762e+07,2.729790e+07,2.312751e+07
13,Experience Cloud,GBP,2.068045e+07,3.308872e+07,3.102067e+07,5.307982e+07,5.226887e+06,5.871527e+06,9.582034e+06,9.397012e+06,...,7.337998e+06,7.196307e+06,8.636195e+06,9.507103e+06,5.080612e+06,9.649578e+06,9.025689e+06,1.795582e+07,7.963999e+06,1.472913e+07
14,Experience Cloud,JPY,9.755124e+06,1.459026e+07,1.503107e+07,2.487557e+07,3.458060e+06,4.090409e+06,2.206655e+06,2.648337e+06,...,2.300109e+08,2.760497e+08,1.120605e+09,1.241628e+08,3.185565e+08,7.177263e+08,5.304824e+08,5.977302e+08,1.029438e+09,9.657399e+08

# Below is from the merge_bookings_to_fcst

In [92]:
dc_list = ["P01_DC", "P02_DC", "P03_DC",
                "P04_DC", "P05_DC", "P06_DC",
                "P07_DC", "P08_DC", "P09_DC",
                "P10_DC", "P11_DC", "P12_DC"
               ]
us_list = ["P01", "P02", "P03",
               "P04", "P05", "P06",
               "P07", "P08", "P09",
               "P10", "P11", "P12"]

df_temp_book_period = df_book_period.drop(
        columns=[
            "Q1",
            "Q2",
            "Q3",
            "Q4",
            "FX_fwd_rate"
        ]
    ).copy()

In [93]:
df_temp_book_period.head(20)

,segment,curr,P01,P02,P03,P04,P05,P06,P07,P08,...,P03_DC,P04_DC,P05_DC,P06_DC,P07_DC,P08_DC,P09_DC,P10_DC,P11_DC,P12_DC
0,Creative,USD,1.138063e+07,8.383721e+06,1.376782e+07,1.157768e+07,8.931597e+06,1.597009e+07,1.222459e+07,1.199205e+07,...,1.376782e+07,1.157768e+07,8.931597e+06,1.597009e+07,1.222459e+07,1.199205e+07,2.173014e+07,1.599765e+07,1.541702e+07,1.883245e+07
1,Creative,AUD,5.323724e+05,3.971506e+05,7.178325e+05,5.519514e+05,6.235560e+05,8.879415e+05,5.170004e+05,6.972151e+05,...,1.002295e+06,7.706787e+05,8.706587e+05,1.239815e+06,7.218774e+05,9.735075e+05,1.336469e+06,1.178340e+06,1.186191e+06,2.878179e+06
2,Creative,EUR,2.191754e+06,1.810889e+06,2.582098e+06,2.530085e+06,2.210486e+06,3.601419e+06,3.879535e+06,3.469331e+06,...,2.195506e+06,2.151281e+06,1.879532e+06,3.062214e+06,3.298691e+06,2.949903e+06,4.166778e+06,4.396264e+06,4.106749e+06,9.180156e+06
3,Creative,GBP,1.231674e+06,9.551193e+05,1.261506e+06,8.898726e+05,1.001382e+06,1.337673e+06,7.043781e+05,7.962808e+05,...,9.660711e+05,6.814716e+05,7.668663e+05,1.024401e+06,5.394184e+05,6.097982e+05,1.907538e+06,1.319331e+06,1.438651e+06,2.106847e+06
4,Creative,JPY,1.058255e+06,9.096653e+05,1.865357e+06,2.044769e+06,2.513401e+06,2.970326e+06,1.148877e+06,1.285973e+06,...,1.944356e+08,2.131367e+08,2.619846e+08,3.096122e+08,1.197533e+08,1.340435e+08,1.831674e+08,1.566849e+08,1.315852e+08,2.592284e+08
5,Document Cloud,USD,7.541640e+06,5.629985e+06,1.045632e+07,7.436849e+06,8.368598e+06,1.278051e+07,1.273265e+07,9.906888e+06,...,1.045632e+07,7.436849e+06,8.368598e+06,1.278051e+07,1.273265e+07,9.906888e+06,1.901259e+07,1.518978e+07,1.801767e+07,2.341324e+07
6,Document Cloud,AUD,5.211134e+05,3.141580e+05,6.032935e+05,4.492348e+05,4.096821e+05,7.734669e+05,5.777254e+05,6.440612e+05,...,8.423667e+05,6.272576e+05,5.720309e+05,1.079976e+06,8.066665e+05,8.992897e+05,1.010003e+06,6.825387e+05,8.805417e+05,1.548881e+06
7,Document Cloud,EUR,1.633802e+06,1.598216e+06,1.818066e+06,1.565634e+06,1.818197e+06,3.578476e+06,2.314511e+06,2.118408e+06,...,1.545865e+06,1.331227e+06,1.545977e+06,3.042706e+06,1.967982e+06,1.801240e+06,2.507150e+06,2.795252e+06,2.575886e+06,7.161975e+06
8,Document Cloud,GBP,1.299257e+06,6.775934e+05,9.653405e+05,6.762189e+05,1.043654e+06,1.757773e+06,9.453755e+05,8.588065e+05,...,7.392655e+05,5.178538e+05,7.992389e+05,1.346116e+06,7.239761e+05,6.576809e+05,1.039450e+06,1.004207e+06,1.324493e+06,2.415249e+06
9,Document Cloud,JPY,3.636555e+05,2.512814e+05,1.062466e+06,5.513015e+05,8.697112e+05,8.995979e+05,6.581845e+05,5.057432e+05,...,1.107462e+08,5.746497e+07,9.065444e+07,9.376968e+07,6.860593e+07,5.271619e+07,9.255536e+07,5.815957e+07,7.932086e+07,1.316622e+08
10,Experience Cloud,USD,7.712481e+07,8.015540e+07,5.548903e+07,1.110184e+08,8.157082e+07,5.462740e+07,9.780503e+07,8.820072e+07,...,5.548903e+07,1.110184e+08,8.157082e+07,5.462740e+07,9.780503e+07,8.820072e+07,1.034146e+08,1.305203e+08,1.026679e+08,1.448665e+08
11,Experience Cloud,AUD,3.446806e+06,3.402949e+06,3.701419e+06,4.984379e+06,4.899854e+06,5.188874e+06,5.215528e+06,4.614628e+06,...,5.168218e+06,6.959589e+06,6.841568e+06,7.245122e+06,7.282337e+06,6.443313e+06,1.258220e+07,6.066906e+06,1.546896e+07,2.160901e+07
12,Experience Cloud,EUR,7.500921e+06,1.825072e+07,9.131240e+06,1.604028e+07,1.199285e+07,2.023605e+07,1.485957e+07,1.798871e+07,...,7.764111e+06,1.363873e+07,1.019728e+07,1.720631e+07,1.263479e+07,1.529544e+07,9.248375e+06,1.899762e+07,2.729790e+07,2.312751e+07
13,Experience Cloud,GBP,5.226887e+06,5.871527e+06,9.582034e+06,9.397012e+06,1.127723e+07,1.241447e+07,6.634316e+06,1.260052e+07,...,7.337998e+06,7.196307e+06,8.636195e+06,9.507103e+06,5.080612e+06,9.649578e+06,9.025689e+06,1.795582e+07,7.963999e+06,1.472913e+07
14,Experience Cloud,JPY,3.458060e+06,4.090409e+06,2.206655e+06,2.648337e+06,1.075075e+07,1.191180e+06,3.056135e+06,6.885649e+06,...,2.300109e+08,2.760497e+08,1.120605e+09,1.241628e+08,3.185565e+08,7.177263e+08,5.304824e+08,5.977302e+08,1.029438e+09,9.657399e+08

In [94]:
df_DC = df_temp_book_period.copy()
df_US = df_temp_book_period.copy()

df_DC = df_DC.drop(columns=us_list)
df_US = df_US.drop(columns=dc_list)

In [95]:
df_US.head(10)

,segment,curr,P01,P02,P03,P04,P05,P06,P07,P08,P09,P10,P11,P12
0,Creative,USD,1.138063e+07,8.383721e+06,1.376782e+07,1.157768e+07,8.931597e+06,1.597009e+07,1.222459e+07,1.199205e+07,2.173014e+07,1.599765e+07,1.541702e+07,1.883245e+07
1,Creative,AUD,5.323724e+05,3.971506e+05,7.178325e+05,5.519514e+05,6.235560e+05,8.879415e+05,5.170004e+05,6.972151e+05,9.571644e+05,8.439141e+05,8.495364e+05,2.061319e+06
2,Creative,EUR,2.191754e+06,1.810889e+06,2.582098e+06,2.530085e+06,2.210486e+06,3.601419e+06,3.879535e+06,3.469331e+06,4.900477e+06,5.170372e+06,4.829879e+06,1.079663e+07
3,Creative,GBP,1.231674e+06,9.551193e+05,1.261506e+06,8.898726e+05,1.001382e+06,1.337673e+06,7.043781e+05,7.962808e+05,2.490883e+06,1.722796e+06,1.878605e+06,2.751143e+06
4,Creative,JPY,1.058255e+06,9.096653e+05,1.865357e+06,2.044769e+06,2.513401e+06,2.970326e+06,1.148877e+06,1.285973e+06,1.757253e+06,1.503187e+06,1.262389e+06,2.486959e+06
5,Document Cloud,USD,7.541640e+06,5.629985e+06,1.045632e+07,7.436849e+06,8.368598e+06,1.278051e+07,1.273265e+07,9.906888e+06,1.901259e+07,1.518978e+07,1.801767e+07,2.341324e+07
6,Document Cloud,AUD,5.211134e+05,3.141580e+05,6.032935e+05,4.492348e+05,4.096821e+05,7.734669e+05,5.777254e+05,6.440612e+05,7.233531e+05,4.888265e+05,6.306341e+05,1.109291e+06
7,Document Cloud,EUR,1.633802e+06,1.598216e+06,1.818066e+06,1.565634e+06,1.818197e+06,3.578476e+06,2.314511e+06,2.118408e+06,2.948617e+06,3.287449e+06,3.029456e+06,8.423078e+06
8,Document Cloud,GBP,1.299257e+06,6.775934e+05,9.653405e+05,6.762189e+05,1.043654e+06,1.757773e+06,9.453755e+05,8.588065e+05,1.357324e+06,1.311304e+06,1.729536e+06,3.153857e+06
9,Document Cloud,JPY,3.636555e+05,2.512814e+05,1.062466e+06,5.513015e+05,8.697112e+05,8.995979e+05,6.581845e+05,5.057432e+05,8.879481e+05,5.579653e+05,7.609803e+05,1.263127e+06

In [96]:
df_DC_melt = pd.melt(df_DC, id_vars=["segment", "curr"])
df_US_melt = pd.melt(df_US, id_vars=["segment", "curr"])

In [97]:
df_US_melt.head(10)

          segment curr variable         value
0        Creative  USD      P01  1.138063e+07
1        Creative  AUD      P01  5.323724e+05
2        Creative  EUR      P01  2.191754e+06
3        Creative  GBP      P01  1.231674e+06
4        Creative  JPY      P01  1.058255e+06
5  Document Cloud  USD      P01  7.541640e+06
6  Document Cloud  AUD      P01  5.211134e+05
7  Document Cloud  EUR      P01  1.633802e+06
8  Document Cloud  GBP      P01  1.299257e+06
9  Document Cloud  JPY      P01  3.636555e+05

In [98]:
df_DC_melt.rename(
        columns={"variable": "period", "value": "book_1Y_DC"}, inplace=True
    )
df_US_melt.rename(
        columns={"variable": "period", "value": "book_1Y_US"}, inplace=True
    )

In [99]:
df_US_melt.head(10)

          segment curr period    book_1Y_US
0        Creative  USD    P01  1.138063e+07
1        Creative  AUD    P01  5.323724e+05
2        Creative  EUR    P01  2.191754e+06
3        Creative  GBP    P01  1.231674e+06
4        Creative  JPY    P01  1.058255e+06
5  Document Cloud  USD    P01  7.541640e+06
6  Document Cloud  AUD    P01  5.211134e+05
7  Document Cloud  EUR    P01  1.633802e+06
8  Document Cloud  GBP    P01  1.299257e+06
9  Document Cloud  JPY    P01  3.636555e+05

In [100]:
df_DC_melt["period"] = df_DC_melt["period"].str.replace("P", "2021-")
df_DC_melt["period"] = df_DC_melt["period"].str.replace("_DC", "")
df_US_melt["period"] = df_US_melt["period"].str.replace("P", "2021-")
df_US_melt["period"] = df_US_melt["period"].str.replace("_US", "")

In [101]:
df_DC_melt.head(10)

          segment curr   period    book_1Y_DC
0        Creative  USD  2021-01  1.138063e+07
1        Creative  AUD  2021-01  7.433410e+05
2        Creative  EUR  2021-01  1.863605e+06
3        Creative  GBP  2021-01  9.432255e+05
4        Creative  JPY  2021-01  1.103074e+08
5  Document Cloud  USD  2021-01  7.541640e+06
6  Document Cloud  AUD  2021-01  7.276202e+05
7  Document Cloud  EUR  2021-01  1.389189e+06
8  Document Cloud  GBP  2021-01  9.949818e+05
9  Document Cloud  JPY  2021-01  3.790567e+07

In [102]:
# reset index
df_DC_melt.set_index(["segment", "curr", "period"], inplace=True)

df_US_melt.set_index(["segment", "curr", "period"], inplace=True)

df_melted = df_DC_melt.join(df_US_melt, how="left")

In [103]:
df_melted.head(10)

                               book_1Y_DC    book_1Y_US
segment        curr period
Creative       USD  2021-01  1.138063e+07  1.138063e+07
               AUD  2021-01  7.433410e+05  5.323724e+05
               EUR  2021-01  1.863605e+06  2.191754e+06
               GBP  2021-01  9.432255e+05  1.231674e+06
               JPY  2021-01  1.103074e+08  1.058255e+06
Document Cloud USD  2021-01  7.541640e+06  7.541640e+06
               AUD  2021-01  7.276202e+05  5.211134e+05
               EUR  2021-01  1.389189e+06  1.633802e+06
               GBP  2021-01  9.949818e+05  1.299257e+06
               JPY  2021-01  3.790567e+07  3.636555e+05

In [104]:
df_melted.sort_index()

                                 book_1Y_DC    book_1Y_US
segment          curr period
Creative         AUD  2021-01  7.433410e+05  5.323724e+05
                      2021-02  5.545334e+05  3.971506e+05
                      2021-03  1.002295e+06  7.178325e+05
                      2021-04  7.706787e+05  5.519514e+05
                      2021-05  8.706587e+05  6.235560e+05
...                                     ...           ...
Experience Cloud USD  2021-08  8.820072e+07  8.820072e+07
                      2021-09  1.034146e+08  1.034146e+08
                      2021-10  1.305203e+08  1.305203e+08
                      2021-11  1.026679e+08  1.026679e+08
                      2021-12  1.448665e+08  1.448665e+08

[180 rows x 2 columns]

In [105]:
df_fcst.head(10)

                       recognized_DC  service_DC  deferred_1M_DC  \
BU       curr period
Creative ARS  2021-01      335626.95         0.0    5.136551e+07
              2021-02       76546.00         0.0    4.341450e+07
              2021-03      170127.00         0.0    5.717074e+07
              2021-04       83775.00         0.0    4.805868e+07
              2021-05      178723.00         0.0    5.038077e+07
              2021-06      161194.19         0.0    6.587858e+07
              2021-07      313318.00         0.0    5.502496e+07
              2021-08      243158.23         0.0    5.734705e+07
              2021-09      200164.71         0.0    7.458642e+07
              2021-10      279809.23         0.0    6.199123e+07

                       deferred_3M_DC  deferred_6M_DC  deferred_1Y_DC  \
BU       curr period
Creative ARS  2021-01             0.0             0.0       916705.92
              2021-02             0.0             0.0      1337025.94
              2021-03             0.0             0.0      2807012.83
              2021-04             0.0             0.0      2940145.60
              2021-05             0.0             0.0      2839892.63
              2021-06             0.0             0.0      3507619.46
              2021-07             0.0             0.0      2366946.53
              2021-08             0.0             0.0      3287724.88
              2021-09             0.0             0.0      5668100.40
              2021-10             0.0             0.0      2854264.08

                       deferred_2Y_DC  deferred_3Y_DC  Period_Weeks  \
BU       curr period
Creative ARS  2021-01             0.0             0.0             5
              2021-02             0.0             0.0             4
              2021-03             0.0             0.0             5
              2021-04             0.0             0.0             4
              2021-05             0.0             0.0             4
              2021-06             0.0             0.0             5
              2021-07             0.0             0.0             4
              2021-08             0.0             0.0             4
              2021-09             0.0             0.0             5
              2021-10             0.0             0.0             4

                       r_squared     intercept          coeff  X_length
BU       curr period
Creative ARS  2021-01   0.981757 -1.062572e+07  580522.899316      23.0
              2021-02   0.981757 -1.062572e+07  580522.899316      23.0
              2021-03   0.981757 -1.062572e+07  580522.899316      23.0
              2021-04   0.981757 -1.062572e+07  580522.899316      23.0
              2021-05   0.981757 -1.062572e+07  580522.899316      23.0
              2021-06   0.981757 -1.062572e+07  580522.899316      23.0
              2021-07   0.981757 -1.062572e+07  580522.899316      23.0
              2021-08   0.981757 -1.062572e+07  580522.899316      23.0
              2021-09   0.981757 -1.062572e+07  580522.899316      23.0
              2021-10   0.981757 -1.062572e+07  580522.899316      23.0

In [106]:
df_fcst.set_index(["BU", "curr", "period"], inplace=True)

KeyError: "None of ['BU', 'curr', 'period'] are in the columns"

In [107]:
df_fcst.head(10)

                       recognized_DC  service_DC  deferred_1M_DC  \
BU       curr period
Creative ARS  2021-01      335626.95         0.0    5.136551e+07
              2021-02       76546.00         0.0    4.341450e+07
              2021-03      170127.00         0.0    5.717074e+07
              2021-04       83775.00         0.0    4.805868e+07
              2021-05      178723.00         0.0    5.038077e+07
              2021-06      161194.19         0.0    6.587858e+07
              2021-07      313318.00         0.0    5.502496e+07
              2021-08      243158.23         0.0    5.734705e+07
              2021-09      200164.71         0.0    7.458642e+07
              2021-10      279809.23         0.0    6.199123e+07

                       deferred_3M_DC  deferred_6M_DC  deferred_1Y_DC  \
BU       curr period
Creative ARS  2021-01             0.0             0.0       916705.92
              2021-02             0.0             0.0      1337025.94
              2021-03             0.0             0.0      2807012.83
              2021-04             0.0             0.0      2940145.60
              2021-05             0.0             0.0      2839892.63
              2021-06             0.0             0.0      3507619.46
              2021-07             0.0             0.0      2366946.53
              2021-08             0.0             0.0      3287724.88
              2021-09             0.0             0.0      5668100.40
              2021-10             0.0             0.0      2854264.08

                       deferred_2Y_DC  deferred_3Y_DC  Period_Weeks  \
BU       curr period
Creative ARS  2021-01             0.0             0.0             5
              2021-02             0.0             0.0             4
              2021-03             0.0             0.0             5
              2021-04             0.0             0.0             4
              2021-05             0.0             0.0             4
              2021-06             0.0             0.0             5
              2021-07             0.0             0.0             4
              2021-08             0.0             0.0             4
              2021-09             0.0             0.0             5
              2021-10             0.0             0.0             4

                       r_squared     intercept          coeff  X_length
BU       curr period
Creative ARS  2021-01   0.981757 -1.062572e+07  580522.899316      23.0
              2021-02   0.981757 -1.062572e+07  580522.899316      23.0
              2021-03   0.981757 -1.062572e+07  580522.899316      23.0
              2021-04   0.981757 -1.062572e+07  580522.899316      23.0
              2021-05   0.981757 -1.062572e+07  580522.899316      23.0
              2021-06   0.981757 -1.062572e+07  580522.899316      23.0
              2021-07   0.981757 -1.062572e+07  580522.899316      23.0
              2021-08   0.981757 -1.062572e+07  580522.899316      23.0
              2021-09   0.981757 -1.062572e+07  580522.899316      23.0
              2021-10   0.981757 -1.062572e+07  580522.899316      23.0

In [68]:
df_fcst.index

MultiIndex([(  'Creative', 'ARS', '2021-01'),
            (  'Creative', 'ARS', '2021-02'),
            (  'Creative', 'ARS', '2021-03'),
            (  'Creative', 'ARS', '2021-04'),
            (  'Creative', 'ARS', '2021-05'),
            (  'Creative', 'ARS', '2021-06'),
            (  'Creative', 'ARS', '2021-07'),
            (  'Creative', 'ARS', '2021-08'),
            (  'Creative', 'ARS', '2021-09'),
            (  'Creative', 'ARS', '2021-10'),
            ...
            ('Publishing', 'USD', '2021-03'),
            ('Publishing', 'USD', '2021-04'),
            ('Publishing', 'USD', '2021-05'),
            ('Publishing', 'USD', '2021-06'),
            ('Publishing', 'USD', '2021-07'),
            ('Publishing', 'USD', '2021-08'),
            ('Publishing', 'USD', '2021-09'),
            ('Publishing', 'USD', '2021-10'),
            ('Publishing', 'USD', '2021-11'),
            ('Publishing', 'USD', '2021-12')],
           names=['BU', 'curr', 'period'], length=2100)

In [108]:
df_fcst = df_fcst.join(df_melted, how="left")

In [109]:
df_fcst.fillna(0, inplace=True)
df_fcst.reset_index(inplace=True)

In [110]:
df_fcst

,curr,period,BU,segment,recognized_DC,service_DC,deferred_1M_DC,deferred_3M_DC,deferred_6M_DC,deferred_1Y_DC,deferred_2Y_DC,deferred_3Y_DC,Period_Weeks,r_squared,intercept,coeff,X_length,book_1Y_DC,book_1Y_US
0,ARS,2021-01,Creative,NaN,3.356270e+05,0.00,5.136551e+07,0.00,0.00,9.167059e+05,0.00,0.0,5,0.981757,-1.062572e+07,580522.899316,23.0,0.000000e+00,0.000000e+00
1,ARS,2021-01,DX Other,NaN,0.000000e+00,0.00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.0,5,0.000000,0.000000e+00,0.000000,0.0,0.000000e+00,0.000000e+00
2,ARS,2021-01,Document Cloud,NaN,0.000000e+00,0.00,1.043530e+06,0.00,0.00,1.648120e+05,0.00,0.0,5,0.958893,-3.204617e+05,14699.104885,23.0,0.000000e+00,0.000000e+00
3,ARS,2021-01,Experience Cloud,NaN,0.000000e+00,0.00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.0,5,0.000000,0.000000e+00,0.000000,0.0,0.000000e+00,0.000000e+00
4,ARS,2021-01,Publishing,NaN,0.000000e+00,0.00,0.000000e+00,0.00,0.00,0.000000e+00,0.00,0.0,5,0.000000,0.000000e+00,0.000000,0.0,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2695,USD,2021-12,Experience Cloud,Document Cloud,2.570486e+07,6895694.93,2.400542e+06,21776724.55,1078986.09,1.152669e+08,0.00,0.0,5,0.179224,1.393309e+06,-15477.974947,19.0,2.341324e+07,2.341324e+07
2696,USD,2021-12,Experience Cloud,Experience Cloud,2.570486e+07,6895694.93,2.400542e+06,21776724.55,1078986.09,1.152669e+08,0.00,0.0,5,0.179224,1.393309e+06,-15477.974947,19.0,1.448665e+08,1.448665e+08
2697,USD,2021-12,Publishing,Creative,4.085561e+07,4951621.21,6.721609e+05,351600.56,178894.49,1.399759e+07,47251.12,0.0,5,0.357839,1.721563e+04,1986.721235,35.0,1.883245e+07,1.883245e+07
2698,USD,2021-12,Publishing,Document Cloud,4.085561e+07,4951621.21,6.721609e+05,351600.56,178894.49,1.399759e+07,47251.12,0.0,5,0.357839,1.721563e+04,1986.721235,35.0,2.341324e+07,2.341324e+07
2699,USD,2021-12,Publishing,Experience Cloud,4.085561e+07,4951621.21,6.721609e+05,351600.56,178894.49,1.399759e+07,47251.12,0.0,5,0.357839,1.721563e+04,1986.721235,35.0,1.448665e+08,1.448665e+08

In [111]:
df_fcst.book_1Y_US.sum()

10456945848.951334

In [64]:
df_fcst = import_thing['forecast']

In [32]:
import_thing = pickle.load(open('/Volumes/Treasury/Financial_Database/Deferred_Revenue/Inputs/Data_2020_p12/processed/intermediate/int_output_5.p', "rb"))
#df_billings = import_thing["billings"]
#df_bookings = import_thing["bookings"]
df_fcst = import_thing['forecast']

In [65]:
df_fcst.head(10)

                       recognized_DC  service_DC  deferred_1M_DC  \
BU       curr period
Creative ARS  2021-01      335626.95         0.0    5.136551e+07
              2021-02       76546.00         0.0    4.341450e+07
              2021-03      170127.00         0.0    5.717074e+07
              2021-04       83775.00         0.0    4.805868e+07
              2021-05      178723.00         0.0    5.038077e+07
              2021-06      161194.19         0.0    6.587858e+07
              2021-07      313318.00         0.0    5.502496e+07
              2021-08      243158.23         0.0    5.734705e+07
              2021-09      200164.71         0.0    7.458642e+07
              2021-10      279809.23         0.0    6.199123e+07

                       deferred_3M_DC  deferred_6M_DC  deferred_1Y_DC  \
BU       curr period
Creative ARS  2021-01             0.0             0.0       916705.92
              2021-02             0.0             0.0      1337025.94
              2021-03             0.0             0.0      2807012.83
              2021-04             0.0             0.0      2940145.60
              2021-05             0.0             0.0      2839892.63
              2021-06             0.0             0.0      3507619.46
              2021-07             0.0             0.0      2366946.53
              2021-08             0.0             0.0      3287724.88
              2021-09             0.0             0.0      5668100.40
              2021-10             0.0             0.0      2854264.08

                       deferred_2Y_DC  deferred_3Y_DC  Period_Weeks  \
BU       curr period
Creative ARS  2021-01             0.0             0.0             5
              2021-02             0.0             0.0             4
              2021-03             0.0             0.0             5
              2021-04             0.0             0.0             4
              2021-05             0.0             0.0             4
              2021-06             0.0             0.0             5
              2021-07             0.0             0.0             4
              2021-08             0.0             0.0             4
              2021-09             0.0             0.0             5
              2021-10             0.0             0.0             4

                       r_squared     intercept          coeff  X_length
BU       curr period
Creative ARS  2021-01   0.981757 -1.062572e+07  580522.899316      23.0
              2021-02   0.981757 -1.062572e+07  580522.899316      23.0
              2021-03   0.981757 -1.062572e+07  580522.899316      23.0
              2021-04   0.981757 -1.062572e+07  580522.899316      23.0
              2021-05   0.981757 -1.062572e+07  580522.899316      23.0
              2021-06   0.981757 -1.062572e+07  580522.899316      23.0
              2021-07   0.981757 -1.062572e+07  580522.899316      23.0
              2021-08   0.981757 -1.062572e+07  580522.899316      23.0
              2021-09   0.981757 -1.062572e+07  580522.899316      23.0
              2021-10   0.981757 -1.062572e+07  580522.899316      23.0