In [8]:
import pandas as pd
import numpy as np

In [9]:
book_FX_rates = pd.read_excel('../data/Data_2019_P06/FX_forward_rates.xlsx', sheet_name='forward_data', 
                        header=1,   index_col=1)

In [10]:
# drop any columns that contain all nas
book_FX_rates.dropna(how='all', axis='columns', inplace=True)

In [11]:
# first rename one of the unnamed columns that you intend to keep
# then delete the other unnamed columns
book_FX_rates.rename( columns={'Unnamed: 2': 'Currency', 'FWD REF':'forward'}, inplace=True)

In [12]:
book_FX_rates.drop(['Pricing Date', 91, 'PX ASK', '% Change', 'SPOT', 'FWD'], axis=1, inplace=True)

In [13]:
book_FX_rates.set_index('Currency', inplace=True)

In [14]:
book_FX_rates

               forward
Currency
AED           3.673964
AUD           1.439320
BBD           2.013300
BMD           1.000000
BRL           3.954754
CAD           1.349750
CHF           0.993608
CLP         711.160000
COP        3399.421300
CNH           6.948031
CZK          23.169652
DKK           6.638631
EUR           0.889192
GBP           0.789246
HKD           7.830982
ILS           3.605797
INR          70.273850
JPY         107.615200
KRW        1186.041700
MDL          18.320000
MXN          19.927751
NOK           8.744978
NZD           1.532282
PLN           3.831749
RON           4.264321
RUB          66.334900
SEK           9.441049
SGD           1.375897
TRY           6.182971
TWD          31.599667
UAH          27.266400
ZAR          14.796300
PHP          52.508966
ARS          51.396600
BHD           0.377279
EGP          16.802700
IDR       14511.090000
JOD           0.712000
KWD           0.304503
LBP        1515.430000
MYR           4.193667
OMR           0.385725
PEN           3.399400
QAR           3.657550
SAR           3.751707
THB          31.510250